import { HomePage } from "./pages/Home/Home";
import { getUsers } from "../services/users";

export const metadata = {
  title: "Home | PeopleAdmin",
  description: "Generated by create next app",
};

export default async function Home() {
  const users = await getUsers();

  return <HomePage />;
}
